name: CI

on:
  pull_request:
  push:
  merge_group:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.9.0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format
